# -*- coding: utf-8 -*-
"""
/***************************************************************************
 pluginSurvol
                                 A QGIS plugin
 C'est un plugin pour générer des itinéraires de survol
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-16
        copyright            : (C) 2023 by PNMercantour
        email                : eric.chraibi@mercantour-parcnational.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load pluginSurvol class from file pluginSurvol.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .AutorisationSurvol import pluginSurvol
    return pluginSurvol(iface)
